export const dynamic = 'force-dynamic';
export const revalidate = 0;

import { Metadata } from 'next';

import prisma from '@/app/lib/prisma';
import { TodoNew, TodosGrid } from '@/todos';
import { getUserSessionServer } from '@/auth/actions/auth-actions';
import { redirect } from 'next/navigation';

export const metadata: Metadata = {
  title: 'list of TODOS',
  description: 'Generated by create next app',
};

export default async function ServerTodosPage() {
  const userSession = await getUserSessionServer();

  if (!userSession) redirect('/api/auth/signin');

  const todos = await prisma.todo.findMany({
    where: { userId: userSession?.id },
    orderBy: { description: 'asc' },
  });

  return (
    <>
      <span className='text-3xl mb-10'>Server Actions</span>

      <div className='w-full px-4 mx-5 mb-5'>
        <TodoNew />
      </div>

      <TodosGrid todos={todos} />
    </>
  );
}
