import { Metadata } from 'next';
import { cookies } from 'next/headers';

import { ItemCard } from '@/shopping-cart/components/ItemCard';
import type { Product } from '@/products/data/products';
import { products } from '@/products/data/products';
import { WidgetItem } from '@/components';

export const metadata: Metadata = {
  title: 'Cart Page',
  description: 'Generated by create next app',
};

interface ProductQuantity {
  product: Product;
  quantity: number;
}

const getProductQuantity = (cart: { [id: string]: number }): ProductQuantity[] => {
  const productsQuantity: ProductQuantity[] = [];

  for (const key in cart) {
    if (Object.prototype.hasOwnProperty.call(cart, key)) {
      const quantity = cart[key];

      const product = products.find((product) => product.id === key);

      if (product)
        productsQuantity.push({
          product,
          quantity,
        });
    }
  }

  return productsQuantity;
};

export default function CartPage() {
  const cookieStore = cookies();
  const cart = JSON.parse(cookieStore.get('cart')?.value ?? '{}');
  const productsQuantity = getProductQuantity(cart);

  const totalToPay = productsQuantity.reduce(
    (prev, current) => current.product.price * current.quantity + prev,
    0
  );

  return (
    <div className=''>
      <h1 className='text-5xl'>Products in cart</h1>
      <hr className='mb-2' />
      <div className='flex flex-col sm:flex-row gap-2 w-full'>
        <div className='flex flex-col gap-2  w-full sm:w-8/12'>
          {productsQuantity.map((productQuantity) => (
            <ItemCard
              key={productQuantity.product.id}
              product={productQuantity.product}
              quantity={productQuantity.quantity}
            />
          ))}
        </div>

        <div className='flex flex-col w-full sm:w-4/12'>
          <WidgetItem title='Total to paid'>
            <div className='mt-2 flex flex-col justify-center items-center gap-4'>
              <h3 className='text-3xl font-bold text-gray-700'>
                ${(totalToPay * 1.15)?.toFixed(2)}
              </h3>
              <span className='font-bold text-center'>
                Taxes 15%: ${(totalToPay * 0.15)?.toFixed(2)}
              </span>
            </div>
          </WidgetItem>
        </div>
      </div>
    </div>
  );
}
