import { Metadata } from 'next';

import prisma from '@/app/lib/prisma';
import { TodosGrid } from '@/todos';

export const metadata: Metadata = {
  title: 'list of TODOS',
  description: 'Generated by create next app',
};

export default async function RestTodosPage() {
  const todos = await prisma.todo.findMany({ orderBy: { description: 'asc' } });

  return (
    <div>
      <TodosGrid todos={todos} />
    </div>
  );
}
